services:
  db:
    image: postgres:15
    container_name: test_db
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./docker/backups:/backups
    ports:
      - "5433:5432"

  web:
    image: nginx:alpine
    container_name: test_web
    ports:
      - "8080:80"
    volumes:
      - ./docker/html:/usr/share/nginx/html
    depends_on:
      - db

volumes:
  pgdata:
    driver: local
