---
- name: Mise a jour des paquets
  apt:
    update_cache: yes

- name: Installation de Nginx
  apt:
    name: nginx
    state: present

- name: Demarrage de Nginx
  service:
    name: nginx
    state: started
    enabled: yes
