apiVersion: v1
kind: Secret
metadata:
  name: wordpress-secret
type: Opaque
stringData:
  MARIADB_ROOT_PASSWORD: root_pass_secret_2026
  MARIADB_DATABASE: wordpress
  MARIADB_USER: wp_user
  MARIADB_PASSWORD: wp_pass_secret_2026
